services:
  development:
    image: zetti.development
    build:
      context: .
      dockerfile: development.dockerfile
    volumes:
      - type: bind
        source: ./client
        target: /tmp/client
      - type: bind
        source: ./overview
        target: /tmp/overview
      - type: bind
        source: ./server
        target: /tmp/server
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
          pids: 20
        reservations:
          cpus: '1.00'
          memory: 1G
